<?php
/**
 * BackendCronjobCronjob_idPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class BackendCronjobCronjob_idPath implements \JsonSerializable
{
    protected ?string $cronjob_id = null;
    public function setCronjob_id(?string $cronjob_id) : void
    {
        $this->cronjob_id = $cronjob_id;
    }
    public function getCronjob_id() : ?string
    {
        return $this->cronjob_id;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('cronjob_id' => $this->cronjob_id), static function ($value) : bool {
            return $value !== null;
        });
    }
}
