<?php
/**
 * BackendUserUserIdPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Key;

class BackendUserUserIdPath implements \JsonSerializable
{
    #[Key('user_id')]
    protected ?string $userId = null;
    public function setUserId(?string $userId) : void
    {
        $this->userId = $userId;
    }
    public function getUserId() : ?string
    {
        return $this->userId;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('user_id' => $this->userId), static function ($value) : bool {
            return $value !== null;
        });
    }
}
