<?php
/**
 * BackendGeneratorByProviderResource automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use GuzzleHttp\Client;
use PSX\Schema\SchemaManager;
use Sdkgen\Client\ResourceAbstract;

class BackendGeneratorByProviderResource extends ResourceAbstract
{
    private string $url;

    private string $provider;

    public function __construct(string $provider, string $baseUrl, ?Client $httpClient = null, ?SchemaManager $schemaManager = null)
    {
        parent::__construct($baseUrl, $httpClient, $schemaManager);

        $this->provider = $provider;
        $this->url = $this->baseUrl . '/backend/generator/' . $provider . '';
    }

    /**
     * @return FormContainer
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function backendActionGeneratorForm(): FormContainer
    {
        $options = [
        ];

        $response = $this->httpClient->request('GET', $this->url, $options);
        $data     = (string) $response->getBody();

        return $this->parse($data, FormContainer::class);
    }

    /**
     * @param GeneratorProvider $data
     * @return Message
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function backendActionGeneratorCreate(GeneratorProvider $data): Message
    {
        $options = [
            'json' => $data
        ];

        $response = $this->httpClient->request('POST', $this->url, $options);
        $data     = (string) $response->getBody();

        return $this->parse($data, Message::class);
    }

    /**
     * @param GeneratorProviderConfig $data
     * @return GeneratorProviderChangelog
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function backendActionGeneratorChangelog(GeneratorProviderConfig $data): GeneratorProviderChangelog
    {
        $options = [
            'json' => $data
        ];

        $response = $this->httpClient->request('PUT', $this->url, $options);
        $data     = (string) $response->getBody();

        return $this->parse($data, GeneratorProviderChangelog::class);
    }

}
