<?php
/**
 * Backend_Page_Create automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_Page_Create extends Page_Create
{
}
