<?php
/**
 * Backend_Event_Update automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_Event_Update extends Event_Update
{
}
