<?php
/**
 * BackendAppAppIdPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Key;

class BackendAppAppIdPath implements \JsonSerializable
{
    #[Key('app_id')]
    protected ?string $appId = null;
    public function setAppId(?string $appId) : void
    {
        $this->appId = $appId;
    }
    public function getAppId() : ?string
    {
        return $this->appId;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('app_id' => $this->appId), static function ($value) : bool {
            return $value !== null;
        });
    }
}
