<?php
/**
 * Backend_Marketplace_Install automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_Marketplace_Install extends Marketplace_Install
{
}
