<?php
/**
 * Backend_User_Collection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_User_Collection extends User_Collection
{
}
