<?php
/**
 * BackendAppAppIdTokenTokenIdPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Key;

class BackendAppAppIdTokenTokenIdPath implements \JsonSerializable
{
    #[Key('app_id')]
    protected ?string $appId = null;
    #[Key('token_id')]
    protected ?string $tokenId = null;
    public function setAppId(?string $appId) : void
    {
        $this->appId = $appId;
    }
    public function getAppId() : ?string
    {
        return $this->appId;
    }
    public function setTokenId(?string $tokenId) : void
    {
        $this->tokenId = $tokenId;
    }
    public function getTokenId() : ?string
    {
        return $this->tokenId;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('app_id' => $this->appId, 'token_id' => $this->tokenId), static function ($value) : bool {
            return $value !== null;
        });
    }
}
