<?php
/**
 * BackendAppApp_idPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class BackendAppApp_idPath implements \JsonSerializable
{
    protected ?string $app_id = null;
    public function setApp_id(?string $app_id) : void
    {
        $this->app_id = $app_id;
    }
    public function getApp_id() : ?string
    {
        return $this->app_id;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('app_id' => $this->app_id), static function ($value) : bool {
            return $value !== null;
        });
    }
}
