<?php
/**
 * Backend_Role_Create automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_Role_Create extends Role_Create
{
}
