<?php
/**
 * Backend_Trash_Restore automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_Trash_Restore extends Trash_Restore
{
}
