<?php
/**
 * Backend_Category_Create automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class Backend_Category_Create extends Category_Create
{
}
