<?php
/**
 * CategoryUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class CategoryUpdate extends Category implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
