<?php
/**
 * Dashboard_Requests automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

/**
 * @extends Collection<Dashboard_Request>
 */
class Dashboard_Requests extends Collection
{
}
