<?php
/**
 * MarketplaceApp automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Key;

class MarketplaceApp implements \JsonSerializable
{
    protected ?string $version = null;
    protected ?string $description = null;
    protected ?string $screenshot = null;
    protected ?string $website = null;
    protected ?string $downloadUrl = null;
    #[Key('sha1Hash')]
    protected ?string $shaHash = null;
    public function setVersion(?string $version) : void
    {
        $this->version = $version;
    }
    public function getVersion() : ?string
    {
        return $this->version;
    }
    public function setDescription(?string $description) : void
    {
        $this->description = $description;
    }
    public function getDescription() : ?string
    {
        return $this->description;
    }
    public function setScreenshot(?string $screenshot) : void
    {
        $this->screenshot = $screenshot;
    }
    public function getScreenshot() : ?string
    {
        return $this->screenshot;
    }
    public function setWebsite(?string $website) : void
    {
        $this->website = $website;
    }
    public function getWebsite() : ?string
    {
        return $this->website;
    }
    public function setDownloadUrl(?string $downloadUrl) : void
    {
        $this->downloadUrl = $downloadUrl;
    }
    public function getDownloadUrl() : ?string
    {
        return $this->downloadUrl;
    }
    public function setShaHash(?string $shaHash) : void
    {
        $this->shaHash = $shaHash;
    }
    public function getShaHash() : ?string
    {
        return $this->shaHash;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('version' => $this->version, 'description' => $this->description, 'screenshot' => $this->screenshot, 'website' => $this->website, 'downloadUrl' => $this->downloadUrl, 'sha1Hash' => $this->shaHash), static function ($value) : bool {
            return $value !== null;
        });
    }
}
