<?php
/**
 * Plan_Create automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Required;

#[Required(array('name', 'price'))]
class Plan_Create extends Plan implements \JsonSerializable
{
}
