<?php
/**
 * Plan_Collection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

/**
 * @extends Collection<Plan>
 */
class Plan_Collection extends Collection
{
}
