<?php
/**
 * RoleCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Required;

#[Required(array('categoryId', 'name'))]
class RoleCreate extends Role implements \JsonSerializable
{
}
