<?php
/**
 * Route_Methods automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

/**
 * @extends \PSX\Record\Record<Route_Method>
 */
class Route_Methods extends \PSX\Record\Record
{
}
