<?php
/**
 * Schema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Pattern;

class Schema implements \JsonSerializable
{
    protected ?int $id = null;
    protected ?int $status = null;
    #[Pattern('^[a-zA-Z0-9\\-\\_]{3,255}$')]
    protected ?string $name = null;
    protected ?SchemaSource $source = null;
    protected ?SchemaForm $form = null;
    protected ?Metadata $metadata = null;
    public function setId(?int $id) : void
    {
        $this->id = $id;
    }
    public function getId() : ?int
    {
        return $this->id;
    }
    public function setStatus(?int $status) : void
    {
        $this->status = $status;
    }
    public function getStatus() : ?int
    {
        return $this->status;
    }
    public function setName(?string $name) : void
    {
        $this->name = $name;
    }
    public function getName() : ?string
    {
        return $this->name;
    }
    public function setSource(?SchemaSource $source) : void
    {
        $this->source = $source;
    }
    public function getSource() : ?SchemaSource
    {
        return $this->source;
    }
    public function setForm(?SchemaForm $form) : void
    {
        $this->form = $form;
    }
    public function getForm() : ?SchemaForm
    {
        return $this->form;
    }
    public function setMetadata(?Metadata $metadata) : void
    {
        $this->metadata = $metadata;
    }
    public function getMetadata() : ?Metadata
    {
        return $this->metadata;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('id' => $this->id, 'status' => $this->status, 'name' => $this->name, 'source' => $this->source, 'form' => $this->form, 'metadata' => $this->metadata), static function ($value) : bool {
            return $value !== null;
        });
    }
}
