<?php
/**
 * SchemaSource automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

use PSX\Schema\Attribute\Description;
/**
 * @extends \PSX\Record\Record<mixed>
 */
#[Description('Contains the TypeSchema specification')]
class SchemaSource extends \PSX\Record\Record
{
}
