<?php
/**
 * ScopeUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class ScopeUpdate extends Scope implements \JsonSerializable
{
}
