<?php
/**
 * Sdk_Types automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;

/**
 * @extends \PSX\Record\Record<string>
 */
class Sdk_Types extends \PSX\Record\Record
{
}
