<?php
/**
 * SdkResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Backend;


class SdkResponse implements \JsonSerializable
{
    protected ?SdkTypes $types = null;
    public function setTypes(?SdkTypes $types) : void
    {
        $this->types = $types;
    }
    public function getTypes() : ?SdkTypes
    {
        return $this->types;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('types' => $this->types), static function ($value) : bool {
            return $value !== null;
        });
    }
}
