<?php
/**
 * Consumer_Page automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class Consumer_Page extends Page
{
}
