<?php
/**
 * Consumer_User_Login automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class Consumer_User_Login extends User_Login
{
}
