<?php
/**
 * Consumer_Authorize_Meta automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class Consumer_Authorize_Meta extends Authorize_Meta
{
}
