<?php
/**
 * Consumer_Event_Subscription automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class Consumer_Event_Subscription extends Event_Subscription
{
}
