<?php
/**
 * ConsumerLogLogIdPath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;

use PSX\Schema\Attribute\Key;

class ConsumerLogLogIdPath implements \JsonSerializable
{
    #[Key('log_id')]
    protected ?string $logId = null;
    public function setLogId(?string $logId) : void
    {
        $this->logId = $logId;
    }
    public function getLogId() : ?string
    {
        return $this->logId;
    }
    public function jsonSerialize() : object
    {
        return (object) array_filter(array('log_id' => $this->logId), static function ($value) : bool {
            return $value !== null;
        });
    }
}
