<?php
/**
 * ConsumerEventSubscription automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class ConsumerEventSubscription extends EventSubscription
{
}
