<?php
/**
 * Consumer_Event_Subscription_Create automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class Consumer_Event_Subscription_Create extends Event_Subscription_Create
{
}
