<?php
/**
 * Consumer_App_Update automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;


class Consumer_App_Update extends App_Update
{
}
