<?php
/**
 * EventCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk\Consumer;

/**
 * @extends Collection<Event>
 */
class EventCollection extends Collection
{
}
