<?php
/**
 * BackendOperationThrows automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

/**
 * @extends \PSX\Record\Record<string>
 */
class BackendOperationThrows extends \PSX\Record\Record
{
}
