<?php
/**
 * BackendIdentityCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class BackendIdentityCreate extends BackendIdentity implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
