<?php
/**
 * BackendCategoryCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Required;

#[Required(array('name'))]
class BackendCategoryCreate extends BackendCategory implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
