<?php
/**
 * BackendTaxonomyUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class BackendTaxonomyUpdate extends BackendTaxonomy implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
