<?php
/**
 * BackendPageCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends CommonCollection<BackendPage>
 */
#[Description('A paginated collection of page objects')]
class BackendPageCollection extends CommonCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
