<?php
/**
 * BackendRoleCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

/**
 * @extends CommonCollection<BackendRole>
 */
class BackendRoleCollection extends CommonCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
