<?php
/**
 * BackendEventSubscriptionCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class BackendEventSubscriptionCreate extends BackendEventSubscription implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
