<?php
/**
 * BackendAuditObject automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends \PSX\Record\Record<mixed>
 */
#[Description('A key value object containing the changes')]
class BackendAuditObject extends \PSX\Record\Record
{
}
