<?php
/**
 * BackendAgentTools automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Represents a collection of available tools')]
class BackendAgentTools implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<BackendAgentTool>|null
     */
    protected ?array $tools = null;
    /**
     * @param array<BackendAgentTool>|null $tools
     */
    public function setTools(?array $tools): void
    {
        $this->tools = $tools;
    }
    /**
     * @return array<BackendAgentTool>|null
     */
    public function getTools(): ?array
    {
        return $this->tools;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('tools', $this->tools);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
