<?php
/**
 * BackendEventCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class BackendEventCreate extends BackendEvent implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
