<?php
/**
 * BackendSchemaForm automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends \PSX\Record\Record<mixed>
 */
#[Description('Contains a UI vocabulary to describe the UI of the schema')]
class BackendSchemaForm extends \PSX\Record\Record
{
}
