<?php
/**
 * BackendSpecificationChangelog automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Represents structural changelog differences between specification versions')]
class BackendSpecificationChangelog implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Specification content corresponding to the current master definition')]
    protected mixed $master = null;
    #[Description('Specification content corresponding to the target tagged version')]
    protected mixed $tag = null;
    #[Description('Version identifier for the tag release')]
    protected ?string $version = null;
    #[Description('Formatted summary detailing API changes between master and tag')]
    protected ?string $changelog = null;
    public function setMaster(mixed $master): void
    {
        $this->master = $master;
    }
    public function getMaster(): mixed
    {
        return $this->master;
    }
    public function setTag(mixed $tag): void
    {
        $this->tag = $tag;
    }
    public function getTag(): mixed
    {
        return $this->tag;
    }
    public function setVersion(?string $version): void
    {
        $this->version = $version;
    }
    public function getVersion(): ?string
    {
        return $this->version;
    }
    public function setChangelog(?string $changelog): void
    {
        $this->changelog = $changelog;
    }
    public function getChangelog(): ?string
    {
        return $this->changelog;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('master', $this->master);
        $record->put('tag', $this->tag);
        $record->put('version', $this->version);
        $record->put('changelog', $this->changelog);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
