<?php
/**
 * BackendMarketplaceLocalApp automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class BackendMarketplaceLocalApp extends BackendMarketplaceApp implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?BackendMarketplaceApp $remote = null;
    public function setRemote(?BackendMarketplaceApp $remote) : void
    {
        $this->remote = $remote;
    }
    public function getRemote() : ?BackendMarketplaceApp
    {
        return $this->remote;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('remote', $this->remote);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
