<?php
/**
 * BackendPlanUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Payload for updating an existing plan definition')]
class BackendPlanUpdate extends BackendPlan implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
