<?php
/**
 * BackendTestCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends CommonCollection<BackendTest>
 */
#[Description('A paginated collection of test objects')]
class BackendTestCollection extends CommonCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
