<?php
/**
 * BackendSpecificationPublish automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Payload defining configuration parameters for publishing an API specification export')]
class BackendSpecificationPublish implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Target specification format name to output')]
    protected ?string $name = null;
    #[Description('Optional category or entity filter applied to scope the exported specification')]
    protected ?string $filterName = null;
    #[Description('Indicates whether the specification output should be rendered as a standalone unit')]
    protected ?bool $standalone = null;
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setFilterName(?string $filterName): void
    {
        $this->filterName = $filterName;
    }
    public function getFilterName(): ?string
    {
        return $this->filterName;
    }
    public function setStandalone(?bool $standalone): void
    {
        $this->standalone = $standalone;
    }
    public function getStandalone(): ?bool
    {
        return $this->standalone;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('name', $this->name);
        $record->put('filterName', $this->filterName);
        $record->put('standalone', $this->standalone);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
