<?php
/**
 * BackendIdentityCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Payload for creating a new identity provider entity')]
class BackendIdentityCreate extends BackendIdentity implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
