<?php
/**
 * BackendOperationParameters automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends \PSX\Record\Record<BackendOperationSchema>
 */
#[Description('Map of path or query parameters accepted by the operation')]
class BackendOperationParameters extends \PSX\Record\Record
{
}
