<?php
/**
 * BackendConnectionConfig automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class BackendConnectionConfig implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
