<?php
/**
 * BackendAgentResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('This object represents an agent response')]
class BackendAgentResponse implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The output message')]
    protected ?BackendAgentMessage $output = null;
    public function setOutput(?BackendAgentMessage $output): void
    {
        $this->output = $output;
    }
    public function getOutput(): ?BackendAgentMessage
    {
        return $this->output;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('output', $this->output);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
