<?php
/**
 * BackendOperationCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Required;

#[Required(array('httpMethod', 'httpPath', 'httpCode', 'name', 'outgoing', 'action'))]
class BackendOperationCreate extends BackendOperation implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
