<?php
/**
 * BackendConnectionCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends CommonCollection<BackendConnection>
 */
#[Description('A paginated collection of connection objects')]
class BackendConnectionCollection extends CommonCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
