<?php
/**
 * BackendDatabaseRow automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends \PSX\Record\Record<mixed>
 */
#[Description('This object represents a row on a relational table')]
class BackendDatabaseRow extends \PSX\Record\Record
{
}
