<?php
/**
 * BackendAgentCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Payload for creating a new AI agent')]
class BackendAgentCreate extends BackendAgent implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
