<?php
/**
 * BackendFormCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;
/**
 * @extends CommonCollection<BackendForm>
 */
#[Description('A paginated collection of form objects')]
class BackendFormCollection extends CommonCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
