<?php
/**
 * CommonFormElementTextArea automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;


class CommonFormElementTextArea extends CommonFormElement implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    protected ?string $mode = null;
    public function setMode(?string $mode) : void
    {
        $this->mode = $mode;
    }
    public function getMode() : ?string
    {
        return $this->mode;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('mode', $this->mode);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
