<?php
/**
 * CommonFormElementTypeSchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Form element which represents a TypeSchema editor')]
class CommonFormElementTypeSchema extends CommonFormElement implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
