<?php
/**
 * CommonFormElementSelect automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Form element which represents a select element')]
class CommonFormElementSelect extends CommonFormElement implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<CommonFormElementSelectOption>|null
     */
    #[Description('Available options for the select element')]
    protected ?array $options = null;
    /**
     * @param array<CommonFormElementSelectOption>|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }
    /**
     * @return array<CommonFormElementSelectOption>|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = parent::toRecord();
        $record->put('options', $this->options);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
