<?php
/**
 * CommonFormElementConnection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Form element which represents a connection selection')]
class CommonFormElementConnection extends CommonFormElementSelect implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
