<?php
/**
 * ConsumerForm automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Dynamic form configuration entity')]
class ConsumerForm implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Uniquely identifies the object schema type')]
    protected ?string $kind = null;
    #[Description('Unique identifier for the form')]
    protected ?int $id = null;
    #[Description('Name of the form')]
    protected ?string $name = null;
    #[Description('Target action path or route triggered on form submission')]
    protected ?string $action = null;
    #[Description('HTTP method used to submit the form (e.g., POST)')]
    protected ?string $method = null;
    #[Description('JSON Schema validating form structure and data inputs')]
    protected mixed $jsonSchema = null;
    #[Description('UI schema defining control layout and widget presentation options')]
    protected mixed $uiSchema = null;
    #[Description('Custom metadata key-value mapping')]
    protected ?CommonMetadata $metadata = null;
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }
    public function getKind(): ?string
    {
        return $this->kind;
    }
    public function setId(?int $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setName(?string $name): void
    {
        $this->name = $name;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setAction(?string $action): void
    {
        $this->action = $action;
    }
    public function getAction(): ?string
    {
        return $this->action;
    }
    public function setMethod(?string $method): void
    {
        $this->method = $method;
    }
    public function getMethod(): ?string
    {
        return $this->method;
    }
    public function setJsonSchema(mixed $jsonSchema): void
    {
        $this->jsonSchema = $jsonSchema;
    }
    public function getJsonSchema(): mixed
    {
        return $this->jsonSchema;
    }
    public function setUiSchema(mixed $uiSchema): void
    {
        $this->uiSchema = $uiSchema;
    }
    public function getUiSchema(): mixed
    {
        return $this->uiSchema;
    }
    public function setMetadata(?CommonMetadata $metadata): void
    {
        $this->metadata = $metadata;
    }
    public function getMetadata(): ?CommonMetadata
    {
        return $this->metadata;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('kind', $this->kind);
        $record->put('id', $this->id);
        $record->put('name', $this->name);
        $record->put('action', $this->action);
        $record->put('method', $this->method);
        $record->put('jsonSchema', $this->jsonSchema);
        $record->put('uiSchema', $this->uiSchema);
        $record->put('metadata', $this->metadata);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
