<?php
/**
 * ConsumerTransaction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

use PSX\Schema\Attribute\Description;

#[Description('Billing transaction record for quota or subscription purchases')]
class ConsumerTransaction implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Uniquely identifies the object schema type')]
    protected ?string $kind = null;
    #[Description('Unique identifier for the transaction record')]
    protected ?int $id = null;
    #[Description('ID of the user who executed the transaction')]
    protected ?int $userId = null;
    #[Description('ID of the subscription plan purchased')]
    protected ?int $planId = null;
    #[Description('Plan details associated with the transaction')]
    protected ?ConsumerPlan $plan = null;
    #[Description('External payment processor transaction reference ID')]
    protected ?string $transactionId = null;
    #[Description('Monetary amount billed for the transaction')]
    protected ?float $amount = null;
    #[Description('Number of points credited to the user account')]
    protected ?float $points = null;
    #[Description('Start timestamp of the active billing period')]
    protected ?\PSX\DateTime\LocalDateTime $periodStart = null;
    #[Description('End timestamp of the active billing period')]
    protected ?\PSX\DateTime\LocalDateTime $periodEnd = null;
    #[Description('Timestamp when the transaction was recorded')]
    protected ?\PSX\DateTime\LocalDateTime $insertDate = null;
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }
    public function getKind(): ?string
    {
        return $this->kind;
    }
    public function setId(?int $id): void
    {
        $this->id = $id;
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setUserId(?int $userId): void
    {
        $this->userId = $userId;
    }
    public function getUserId(): ?int
    {
        return $this->userId;
    }
    public function setPlanId(?int $planId): void
    {
        $this->planId = $planId;
    }
    public function getPlanId(): ?int
    {
        return $this->planId;
    }
    public function setPlan(?ConsumerPlan $plan): void
    {
        $this->plan = $plan;
    }
    public function getPlan(): ?ConsumerPlan
    {
        return $this->plan;
    }
    public function setTransactionId(?string $transactionId): void
    {
        $this->transactionId = $transactionId;
    }
    public function getTransactionId(): ?string
    {
        return $this->transactionId;
    }
    public function setAmount(?float $amount): void
    {
        $this->amount = $amount;
    }
    public function getAmount(): ?float
    {
        return $this->amount;
    }
    public function setPoints(?float $points): void
    {
        $this->points = $points;
    }
    public function getPoints(): ?float
    {
        return $this->points;
    }
    public function setPeriodStart(?\PSX\DateTime\LocalDateTime $periodStart): void
    {
        $this->periodStart = $periodStart;
    }
    public function getPeriodStart(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->periodStart;
    }
    public function setPeriodEnd(?\PSX\DateTime\LocalDateTime $periodEnd): void
    {
        $this->periodEnd = $periodEnd;
    }
    public function getPeriodEnd(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->periodEnd;
    }
    public function setInsertDate(?\PSX\DateTime\LocalDateTime $insertDate): void
    {
        $this->insertDate = $insertDate;
    }
    public function getInsertDate(): ?\PSX\DateTime\LocalDateTime
    {
        return $this->insertDate;
    }
    /**
     * @return \PSX\Record\RecordInterface<mixed>
     */
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('kind', $this->kind);
        $record->put('id', $this->id);
        $record->put('userId', $this->userId);
        $record->put('planId', $this->planId);
        $record->put('plan', $this->plan);
        $record->put('transactionId', $this->transactionId);
        $record->put('amount', $this->amount);
        $record->put('points', $this->points);
        $record->put('periodStart', $this->periodStart);
        $record->put('periodEnd', $this->periodEnd);
        $record->put('insertDate', $this->insertDate);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
