<?php
/**
 * SystemRoutePath automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Sdk;

/**
 * @extends \PSX\Record\Record<SystemRouteMethod>
 */
class SystemRoutePath extends \PSX\Record\Record
{
}
